POST https://swn14-tellyport.deno.dev/api/registration/api-key HTTP/1.1
content-type: application/json

{
    "emailAddress": "swnofer@gmail.com"
}

### 

GET http://localhost:3000/api/tv/random-episode?seriesId=1447
Content-Type: application/json
X-API-Key: c17b242a-ab82-45e9-9ca0-8a79474f875e

###

GET https://sheldonnofe-bramble-scr-68.deno.dev/api/tv/search?query=person of interest
Content-Type: application/json
X-API-Key: c17b242a-ab82-45e9-9ca0-8a79474f875e

###

GET https://sheldonnofe-bramble-scr-68.deno.dev/api/tv/random-episode?seriesId=1411
Content-Type: application/json
X-API-Key: c17b242a-ab82-45e9-9ca0-8a79474f875e