name: "Custom Deploy"
description: "Wraps denoland/deployctl and extends its functionality"
inputs:
  project:
    description: "Deno Deploy project name"
    required: true
  token:
    description: "Deno Deploy API Token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run pre-deploy tasks
      run: |
        echo "Running pre-deploy tasks..."
        deno task build
      shell: bash

    - name: Deploy to Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: ${{ inputs.project }}
        token: ${{ inputs.token }}

    - name: Run post-deploy tasks
      run: echo "Deployment completed!"
      shell: bash
