name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Adjust as needed

      - name: Install dependencies and build client
        run: |
          npm --prefix ./client install
          npm --prefix ./client run build

      - name: Upload client artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client-build

      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          name: client-build
          path: "./"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "sheldonnofe-bramble-scr-68"
          entrypoint: "app.ts"
          root: "./"
